Vagrant.configure("2") do |config|
    config.vm.define "test" do |testing|
        testing.vm.box = ENV["BOX_NAME"] || "ubuntu/focal64"  # Utilizamos una imagen de Ubuntu 20.04 por defecto

        testing.vm.provision "shell", inline: <<-SHELL
            # Instalar ChefDK
            wget -qO- https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk

            export CHEF_LICENSE="accept"

            # Instalar las gemas necesarias para las pruebas
            cd /vagrant/test_database && chef exec bundle install
            cd /vagrant/test_wordpress && chef exec bundle install
            cd /vagrant/test_proxy && chef exec bundle install

            chown -R vagrant:vagrant /opt/chefdk
        SHELL
  end
end