default['wordpress']['database']['name'] = 'wordpress'
default['wordpress']['database']['user'] = 'wordpress'
default['wordpress']['database']['password'] = 'testP@55word'
default['wordpress']['database']['host'] = 'db.unir.mx'
default['wordpress']['database']['charset'] = 'utf8'
default['wordpress']['database']['collate'] = 'utf8_general_ci'