name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - testing

jobs:
  vagrant-up:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Unit tests
      run: |
        cd tests
        ./unit_tests.sh
